name: Build Jar

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: build classes
      run: javac @sources.txt -d ./out
    - name: copy static files
      run: cp -r ./images ./out/images
    - name: build jar
      run: |
        cd ./out
        jar cfe ./mazerunner.jar com.GameDriver ./
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
          './out/mazerunner.jar' \
          --repo="$GITHUB_REPOSITORY" \
          --title="${tag#v}" \
          --generate-notes \
          --latest